version: 0.0
os: linux
files:
  - source: /
  destination: /home/admin/cicd
hooks:
  applicationStop:
    - location: scripts/app_stop.sh
    timeout: 300
    runas: admin
  BeforeInstall:
    -location :scripts/before_install.sh
    timeout: 300
    runas: admin
  ApplicationStart:
  - location : scripts/app_start.sh
    timeout: 300
    runas: admin